### YamlMime:ManagedReference
items:
- uid: Microsoft.Bot.Connector.JwtConfig
  commentId: T:Microsoft.Bot.Connector.JwtConfig
  id: JwtConfig
  children:
  - Microsoft.Bot.Connector.JwtConfig.ToBotFromChannelOpenIdMetadataUrl
  - Microsoft.Bot.Connector.JwtConfig.ToBotFromChannelTokenValidationParameters
  - Microsoft.Bot.Connector.JwtConfig.ToBotFromEmulatorOpenIdMetadataUrl
  - Microsoft.Bot.Connector.JwtConfig.ToBotFromEmulatorTokenValidationParameters
  - Microsoft.Bot.Connector.JwtConfig.ToChannelFromBotLoginUrl
  - Microsoft.Bot.Connector.JwtConfig.ToChannelFromBotOAuthScope
  langs:
  - csharp
  name: JwtConfig
  nameWithType: JwtConfig
  fullName: Microsoft.Bot.Connector.JwtConfig
  type: Class
  assemblies:
  - Microsoft.Bot.Connector
  namespace: Microsoft.Bot.Connector
  summary: Configuration for JWT tokens
  syntax:
    content: public static class JwtConfig
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Connector/JwtConfig.xml
- uid: Microsoft.Bot.Connector.JwtConfig.ToBotFromChannelOpenIdMetadataUrl
  commentId: F:Microsoft.Bot.Connector.JwtConfig.ToBotFromChannelOpenIdMetadataUrl
  id: ToBotFromChannelOpenIdMetadataUrl
  parent: Microsoft.Bot.Connector.JwtConfig
  langs:
  - csharp
  name: ToBotFromChannelOpenIdMetadataUrl
  nameWithType: JwtConfig.ToBotFromChannelOpenIdMetadataUrl
  fullName: JwtConfig.ToBotFromChannelOpenIdMetadataUrl
  type: Field
  assemblies:
  - 
  namespace: Microsoft.Bot.Connector
  summary: 'TO BOT FROM CHANNEL: OpenID metadata document for tokens coming from MSA'
  syntax:
    content: public const string ToBotFromChannelOpenIdMetadataUrl;
    return:
      type: System.String
      description: To be added.
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Connector/JwtConfig.xml
- uid: Microsoft.Bot.Connector.JwtConfig.ToBotFromChannelTokenValidationParameters
  commentId: F:Microsoft.Bot.Connector.JwtConfig.ToBotFromChannelTokenValidationParameters
  id: ToBotFromChannelTokenValidationParameters
  parent: Microsoft.Bot.Connector.JwtConfig
  langs:
  - csharp
  name: ToBotFromChannelTokenValidationParameters
  nameWithType: JwtConfig.ToBotFromChannelTokenValidationParameters
  fullName: JwtConfig.ToBotFromChannelTokenValidationParameters
  type: Field
  assemblies:
  - 
  namespace: Microsoft.Bot.Connector
  summary: 'TO BOT FROM CHANNEL: Token validation parameters when connecting to a bot'
  syntax:
    content: public static readonly System.IdentityModel.Tokens.TokenValidationParameters ToBotFromChannelTokenValidationParameters;
    return:
      type: System.IdentityModel.Tokens.TokenValidationParameters
      description: To be added.
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Connector/JwtConfig.xml
- uid: Microsoft.Bot.Connector.JwtConfig.ToBotFromEmulatorOpenIdMetadataUrl
  commentId: F:Microsoft.Bot.Connector.JwtConfig.ToBotFromEmulatorOpenIdMetadataUrl
  id: ToBotFromEmulatorOpenIdMetadataUrl
  parent: Microsoft.Bot.Connector.JwtConfig
  langs:
  - csharp
  name: ToBotFromEmulatorOpenIdMetadataUrl
  nameWithType: JwtConfig.ToBotFromEmulatorOpenIdMetadataUrl
  fullName: JwtConfig.ToBotFromEmulatorOpenIdMetadataUrl
  type: Field
  assemblies:
  - 
  namespace: Microsoft.Bot.Connector
  summary: 'TO BOT FROM EMULATOR: OpenID metadata document for tokens coming from MSA'
  syntax:
    content: public const string ToBotFromEmulatorOpenIdMetadataUrl;
    return:
      type: System.String
      description: To be added.
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Connector/JwtConfig.xml
- uid: Microsoft.Bot.Connector.JwtConfig.ToBotFromEmulatorTokenValidationParameters
  commentId: F:Microsoft.Bot.Connector.JwtConfig.ToBotFromEmulatorTokenValidationParameters
  id: ToBotFromEmulatorTokenValidationParameters
  parent: Microsoft.Bot.Connector.JwtConfig
  langs:
  - csharp
  name: ToBotFromEmulatorTokenValidationParameters
  nameWithType: JwtConfig.ToBotFromEmulatorTokenValidationParameters
  fullName: JwtConfig.ToBotFromEmulatorTokenValidationParameters
  type: Field
  assemblies:
  - 
  namespace: Microsoft.Bot.Connector
  summary: 'TO BOT FROM EMULATOR: Token validation parameters when connecting to a channel'
  syntax:
    content: public static readonly System.IdentityModel.Tokens.TokenValidationParameters ToBotFromEmulatorTokenValidationParameters;
    return:
      type: System.IdentityModel.Tokens.TokenValidationParameters
      description: To be added.
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Connector/JwtConfig.xml
- uid: Microsoft.Bot.Connector.JwtConfig.ToChannelFromBotLoginUrl
  commentId: F:Microsoft.Bot.Connector.JwtConfig.ToChannelFromBotLoginUrl
  id: ToChannelFromBotLoginUrl
  parent: Microsoft.Bot.Connector.JwtConfig
  langs:
  - csharp
  name: ToChannelFromBotLoginUrl
  nameWithType: JwtConfig.ToChannelFromBotLoginUrl
  fullName: JwtConfig.ToChannelFromBotLoginUrl
  type: Field
  assemblies:
  - 
  namespace: Microsoft.Bot.Connector
  summary: 'TO CHANNEL FROM BOT: Login URL'
  syntax:
    content: public const string ToChannelFromBotLoginUrl;
    return:
      type: System.String
      description: To be added.
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Connector/JwtConfig.xml
- uid: Microsoft.Bot.Connector.JwtConfig.ToChannelFromBotOAuthScope
  commentId: F:Microsoft.Bot.Connector.JwtConfig.ToChannelFromBotOAuthScope
  id: ToChannelFromBotOAuthScope
  parent: Microsoft.Bot.Connector.JwtConfig
  langs:
  - csharp
  name: ToChannelFromBotOAuthScope
  nameWithType: JwtConfig.ToChannelFromBotOAuthScope
  fullName: JwtConfig.ToChannelFromBotOAuthScope
  type: Field
  assemblies:
  - 
  namespace: Microsoft.Bot.Connector
  summary: 'TO CHANNEL FROM BOT: OAuth scope to request'
  syntax:
    content: public const string ToChannelFromBotOAuthScope;
    return:
      type: System.String
      description: To be added.
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Connector/JwtConfig.xml
references:
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.Bot.Connector.JwtConfig.ToBotFromChannelOpenIdMetadataUrl
  parent: Microsoft.Bot.Connector.JwtConfig
  isExternal: false
  name: ToBotFromChannelOpenIdMetadataUrl
  nameWithType: JwtConfig.ToBotFromChannelOpenIdMetadataUrl
  fullName: JwtConfig.ToBotFromChannelOpenIdMetadataUrl
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Bot.Connector.JwtConfig.ToBotFromChannelTokenValidationParameters
  parent: Microsoft.Bot.Connector.JwtConfig
  isExternal: false
  name: ToBotFromChannelTokenValidationParameters
  nameWithType: JwtConfig.ToBotFromChannelTokenValidationParameters
  fullName: JwtConfig.ToBotFromChannelTokenValidationParameters
- uid: System.IdentityModel.Tokens.TokenValidationParameters
  parent: System.IdentityModel.Tokens
  isExternal: true
  name: TokenValidationParameters
  nameWithType: TokenValidationParameters
  fullName: System.IdentityModel.Tokens.TokenValidationParameters
- uid: Microsoft.Bot.Connector.JwtConfig.ToBotFromEmulatorOpenIdMetadataUrl
  parent: Microsoft.Bot.Connector.JwtConfig
  isExternal: false
  name: ToBotFromEmulatorOpenIdMetadataUrl
  nameWithType: JwtConfig.ToBotFromEmulatorOpenIdMetadataUrl
  fullName: JwtConfig.ToBotFromEmulatorOpenIdMetadataUrl
- uid: Microsoft.Bot.Connector.JwtConfig.ToBotFromEmulatorTokenValidationParameters
  parent: Microsoft.Bot.Connector.JwtConfig
  isExternal: false
  name: ToBotFromEmulatorTokenValidationParameters
  nameWithType: JwtConfig.ToBotFromEmulatorTokenValidationParameters
  fullName: JwtConfig.ToBotFromEmulatorTokenValidationParameters
- uid: Microsoft.Bot.Connector.JwtConfig.ToChannelFromBotLoginUrl
  parent: Microsoft.Bot.Connector.JwtConfig
  isExternal: false
  name: ToChannelFromBotLoginUrl
  nameWithType: JwtConfig.ToChannelFromBotLoginUrl
  fullName: JwtConfig.ToChannelFromBotLoginUrl
- uid: Microsoft.Bot.Connector.JwtConfig.ToChannelFromBotOAuthScope
  parent: Microsoft.Bot.Connector.JwtConfig
  isExternal: false
  name: ToChannelFromBotOAuthScope
  nameWithType: JwtConfig.ToChannelFromBotOAuthScope
  fullName: JwtConfig.ToChannelFromBotOAuthScope
