### YamlMime:ManagedReference
items:
- uid: Microsoft.Bot.Connector.SettingsCredentialProvider
  commentId: T:Microsoft.Bot.Connector.SettingsCredentialProvider
  id: SettingsCredentialProvider
  children:
  - Microsoft.Bot.Connector.SettingsCredentialProvider.#ctor(System.String,System.String)
  langs:
  - csharp
  name: SettingsCredentialProvider
  nameWithType: SettingsCredentialProvider
  fullName: Microsoft.Bot.Connector.SettingsCredentialProvider
  type: Class
  assemblies:
  - Microsoft.Bot.Connector
  namespace: Microsoft.Bot.Connector
  summary: Credential provider which uses config settings to lookup appId and password
  syntax:
    content: 'public sealed class SettingsCredentialProvider : Microsoft.Bot.Connector.SimpleCredentialProvider'
  inheritance:
  - System.Object
  - Microsoft.Bot.Connector.SimpleCredentialProvider
  implements: []
  inheritedMembers:
  - Microsoft.Bot.Connector.SimpleCredentialProvider.AppId
  - Microsoft.Bot.Connector.SimpleCredentialProvider.GetAppPasswordAsync(System.String)
  - Microsoft.Bot.Connector.SimpleCredentialProvider.IsAuthenticationDisabledAsync
  - Microsoft.Bot.Connector.SimpleCredentialProvider.IsValidAppIdAsync(System.String)
  - Microsoft.Bot.Connector.SimpleCredentialProvider.Password
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Connector/SettingsCredentialProvider.xml
- uid: Microsoft.Bot.Connector.SettingsCredentialProvider.#ctor(System.String,System.String)
  commentId: M:Microsoft.Bot.Connector.SettingsCredentialProvider.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: Microsoft.Bot.Connector.SettingsCredentialProvider
  langs:
  - csharp
  name: SettingsCredentialProvider(String, String)
  nameWithType: SettingsCredentialProvider.SettingsCredentialProvider(String, String)
  fullName: SettingsCredentialProvider.SettingsCredentialProvider(String, String)
  type: Constructor
  assemblies:
  - 
  namespace: Microsoft.Bot.Connector
  syntax:
    content: public SettingsCredentialProvider (string appIdSettingName = null, string appPasswordSettingName = null);
    parameters:
    - id: appIdSettingName
      type: System.String
      description: To be added.
    - id: appPasswordSettingName
      type: System.String
      description: To be added.
  overload: Microsoft.Bot.Connector.SettingsCredentialProvider.#ctor*
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Connector/SettingsCredentialProvider.xml
references:
- uid: Microsoft.Bot.Connector.SimpleCredentialProvider
  parent: Microsoft.Bot.Connector
  isExternal: false
  name: SimpleCredentialProvider
  nameWithType: SimpleCredentialProvider
  fullName: Microsoft.Bot.Connector.SimpleCredentialProvider
- uid: Microsoft.Bot.Connector.SettingsCredentialProvider.#ctor(System.String,System.String)
  parent: Microsoft.Bot.Connector.SettingsCredentialProvider
  isExternal: false
  name: SettingsCredentialProvider(String, String)
  nameWithType: SettingsCredentialProvider.SettingsCredentialProvider(String, String)
  fullName: SettingsCredentialProvider.SettingsCredentialProvider(String, String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Bot.Connector.SettingsCredentialProvider.#ctor*
  parent: Microsoft.Bot.Connector.SettingsCredentialProvider
  isExternal: false
  name: SettingsCredentialProvider
  nameWithType: SettingsCredentialProvider.SettingsCredentialProvider
  fullName: SettingsCredentialProvider.SettingsCredentialProvider
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Connector/SettingsCredentialProvider.xml
