### YamlMime:ManagedReference
items:
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  commentId: T:Microsoft.Bot.Builder.FormFlow.FormConfiguration
  id: FormConfiguration
  children:
  - Microsoft.Bot.Builder.FormFlow.FormConfiguration.#ctor
  - Microsoft.Bot.Builder.FormFlow.FormConfiguration.Commands
  - Microsoft.Bot.Builder.FormFlow.FormConfiguration.Confirmation
  - Microsoft.Bot.Builder.FormFlow.FormConfiguration.CurrentChoice
  - Microsoft.Bot.Builder.FormFlow.FormConfiguration.DefaultPrompt
  - Microsoft.Bot.Builder.FormFlow.FormConfiguration.Navigation
  - Microsoft.Bot.Builder.FormFlow.FormConfiguration.No
  - Microsoft.Bot.Builder.FormFlow.FormConfiguration.NoPreference
  - Microsoft.Bot.Builder.FormFlow.FormConfiguration.Template(Microsoft.Bot.Builder.FormFlow.TemplateUsage)
  - Microsoft.Bot.Builder.FormFlow.FormConfiguration.Templates
  - Microsoft.Bot.Builder.FormFlow.FormConfiguration.Yes
  langs:
  - csharp
  name: FormConfiguration
  nameWithType: FormConfiguration
  fullName: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  type: Class
  assemblies:
  - Microsoft.Bot.Builder
  namespace: Microsoft.Bot.Builder.FormFlow
  summary: Default values for the form.
  remarks: These defaults can all be overridden when you create a form and before you add steps.
  syntax:
    content: public class FormConfiguration
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Builder.FormFlow/FormConfiguration.xml
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.#ctor
  commentId: M:Microsoft.Bot.Builder.FormFlow.FormConfiguration.#ctor
  id: '#ctor'
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  langs:
  - csharp
  name: FormConfiguration()
  nameWithType: FormConfiguration.FormConfiguration()
  fullName: FormConfiguration.FormConfiguration()
  type: Constructor
  assemblies:
  - 
  namespace: Microsoft.Bot.Builder.FormFlow
  summary: Construct configuration.
  syntax:
    content: public FormConfiguration ();
    parameters: []
  overload: Microsoft.Bot.Builder.FormFlow.FormConfiguration.#ctor*
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Builder.FormFlow/FormConfiguration.xml
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.Commands
  commentId: F:Microsoft.Bot.Builder.FormFlow.FormConfiguration.Commands
  id: Commands
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  langs:
  - csharp
  name: Commands
  nameWithType: FormConfiguration.Commands
  fullName: FormConfiguration.Commands
  type: Field
  assemblies:
  - 
  namespace: Microsoft.Bot.Builder.FormFlow
  summary: Definitions of the built-in commands.
  syntax:
    content: public System.Collections.Generic.Dictionary<Microsoft.Bot.Builder.FormFlow.FormCommand,Microsoft.Bot.Builder.FormFlow.CommandDescription> Commands;
    return:
      type: System.Collections.Generic.Dictionary{Microsoft.Bot.Builder.FormFlow.FormCommand,Microsoft.Bot.Builder.FormFlow.CommandDescription}
      description: To be added.
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Builder.FormFlow/FormConfiguration.xml
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.Confirmation
  commentId: F:Microsoft.Bot.Builder.FormFlow.FormConfiguration.Confirmation
  id: Confirmation
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  langs:
  - csharp
  name: Confirmation
  nameWithType: FormConfiguration.Confirmation
  fullName: FormConfiguration.Confirmation
  type: Field
  assemblies:
  - 
  namespace: Microsoft.Bot.Builder.FormFlow
  summary: String for naming "Confirmation" fields.
  syntax:
    content: public string Confirmation;
    return:
      type: System.String
      description: To be added.
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Builder.FormFlow/FormConfiguration.xml
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.CurrentChoice
  commentId: F:Microsoft.Bot.Builder.FormFlow.FormConfiguration.CurrentChoice
  id: CurrentChoice
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  langs:
  - csharp
  name: CurrentChoice
  nameWithType: FormConfiguration.CurrentChoice
  fullName: FormConfiguration.CurrentChoice
  type: Field
  assemblies:
  - 
  namespace: Microsoft.Bot.Builder.FormFlow
  summary: Enumeration of strings for interpreting a user response as asking for the current value.
  remarks: The first value is also used to describe the option of keeping the current value.
  syntax:
    content: public string[] CurrentChoice;
    return:
      type: System.String[]
      description: To be added.
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Builder.FormFlow/FormConfiguration.xml
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.DefaultPrompt
  commentId: F:Microsoft.Bot.Builder.FormFlow.FormConfiguration.DefaultPrompt
  id: DefaultPrompt
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  langs:
  - csharp
  name: DefaultPrompt
  nameWithType: FormConfiguration.DefaultPrompt
  fullName: FormConfiguration.DefaultPrompt
  type: Field
  assemblies:
  - 
  namespace: Microsoft.Bot.Builder.FormFlow
  summary: Default prompt and template format settings.
  remarks: "When you specify a <xref href=\"Microsoft.Bot.Builder.FormFlow.PromptAttribute\"></xref> or <xref href=\"Microsoft.Bot.Builder.FormFlow.TemplateAttribute\"></xref>, any format \n            value you do not specify will come from this default."
  syntax:
    content: public Microsoft.Bot.Builder.FormFlow.PromptAttribute DefaultPrompt;
    return:
      type: Microsoft.Bot.Builder.FormFlow.PromptAttribute
      description: To be added.
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Builder.FormFlow/FormConfiguration.xml
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.Navigation
  commentId: F:Microsoft.Bot.Builder.FormFlow.FormConfiguration.Navigation
  id: Navigation
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  langs:
  - csharp
  name: Navigation
  nameWithType: FormConfiguration.Navigation
  fullName: FormConfiguration.Navigation
  type: Field
  assemblies:
  - 
  namespace: Microsoft.Bot.Builder.FormFlow
  summary: String for naming the "navigation" field.
  syntax:
    content: public string Navigation;
    return:
      type: System.String
      description: To be added.
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Builder.FormFlow/FormConfiguration.xml
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.No
  commentId: F:Microsoft.Bot.Builder.FormFlow.FormConfiguration.No
  id: No
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  langs:
  - csharp
  name: No
  nameWithType: FormConfiguration.No
  fullName: FormConfiguration.No
  type: Field
  assemblies:
  - 
  namespace: Microsoft.Bot.Builder.FormFlow
  summary: Enumeration of values for a "no" response for boolean fields or confirmations.
  syntax:
    content: public string[] No;
    return:
      type: System.String[]
      description: To be added.
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Builder.FormFlow/FormConfiguration.xml
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.NoPreference
  commentId: F:Microsoft.Bot.Builder.FormFlow.FormConfiguration.NoPreference
  id: NoPreference
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  langs:
  - csharp
  name: NoPreference
  nameWithType: FormConfiguration.NoPreference
  fullName: FormConfiguration.NoPreference
  type: Field
  assemblies:
  - 
  namespace: Microsoft.Bot.Builder.FormFlow
  summary: Enumeration of strings for interpreting a user response as setting an optional field to be unspecified.
  remarks: The first string is also used to describe not having a preference for an optional field.
  syntax:
    content: public string[] NoPreference;
    return:
      type: System.String[]
      description: To be added.
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Builder.FormFlow/FormConfiguration.xml
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.Template(Microsoft.Bot.Builder.FormFlow.TemplateUsage)
  commentId: M:Microsoft.Bot.Builder.FormFlow.FormConfiguration.Template(Microsoft.Bot.Builder.FormFlow.TemplateUsage)
  id: Template(Microsoft.Bot.Builder.FormFlow.TemplateUsage)
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  langs:
  - csharp
  name: Template(TemplateUsage)
  nameWithType: FormConfiguration.Template(TemplateUsage)
  fullName: FormConfiguration.Template(TemplateUsage)
  type: Method
  assemblies:
  - 
  namespace: Microsoft.Bot.Builder.FormFlow
  summary: Look up a particular template.
  syntax:
    content: public Microsoft.Bot.Builder.FormFlow.TemplateAttribute Template (Microsoft.Bot.Builder.FormFlow.TemplateUsage usage);
    parameters:
    - id: usage
      type: Microsoft.Bot.Builder.FormFlow.TemplateUsage
      description: Desired template.
    return:
      type: Microsoft.Bot.Builder.FormFlow.TemplateAttribute
      description: Matching template.
  overload: Microsoft.Bot.Builder.FormFlow.FormConfiguration.Template*
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Builder.FormFlow/FormConfiguration.xml
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.Templates
  commentId: F:Microsoft.Bot.Builder.FormFlow.FormConfiguration.Templates
  id: Templates
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  langs:
  - csharp
  name: Templates
  nameWithType: FormConfiguration.Templates
  fullName: FormConfiguration.Templates
  type: Field
  assemblies:
  - 
  namespace: Microsoft.Bot.Builder.FormFlow
  summary: Default templates to use if not override on the class or field level.
  syntax:
    content: public System.Collections.Generic.List<Microsoft.Bot.Builder.FormFlow.TemplateAttribute> Templates;
    return:
      type: System.Collections.Generic.List{Microsoft.Bot.Builder.FormFlow.TemplateAttribute}
      description: To be added.
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Builder.FormFlow/FormConfiguration.xml
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.Yes
  commentId: F:Microsoft.Bot.Builder.FormFlow.FormConfiguration.Yes
  id: Yes
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  langs:
  - csharp
  name: Yes
  nameWithType: FormConfiguration.Yes
  fullName: FormConfiguration.Yes
  type: Field
  assemblies:
  - 
  namespace: Microsoft.Bot.Builder.FormFlow
  summary: Enumeration of values for a "yes" response for boolean fields or confirmations.
  syntax:
    content: public string[] Yes;
    return:
      type: System.String[]
      description: To be added.
  exceptions: []
  version:
  - botbuilder-3.5.5
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Builder.FormFlow/FormConfiguration.xml
references:
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.#ctor
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  isExternal: false
  name: FormConfiguration()
  nameWithType: FormConfiguration.FormConfiguration()
  fullName: FormConfiguration.FormConfiguration()
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.Commands
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  isExternal: false
  name: Commands
  nameWithType: FormConfiguration.Commands
  fullName: FormConfiguration.Commands
- uid: System.Collections.Generic.Dictionary`2
  name: Dictionary
  nameWithType: Dictionary
  fullName: System.Collections.Generic.Dictionary
- uid: Microsoft.Bot.Builder.FormFlow.FormCommand
  name: FormCommand
  nameWithType: FormCommand
  fullName: Microsoft.Bot.Builder.FormFlow.FormCommand
- uid: Microsoft.Bot.Builder.FormFlow.CommandDescription
  name: CommandDescription
  nameWithType: CommandDescription
  fullName: Microsoft.Bot.Builder.FormFlow.CommandDescription
- uid: System.Collections.Generic.Dictionary{Microsoft.Bot.Builder.FormFlow.FormCommand,Microsoft.Bot.Builder.FormFlow.CommandDescription}
  parent: System.Collections.Generic
  isExternal: true
  name: Dictionary<FormCommand,CommandDescription>
  nameWithType: Dictionary<FormCommand,CommandDescription>
  fullName: System.Collections.Generic.Dictionary<Microsoft.Bot.Builder.FormFlow.FormCommand,Microsoft.Bot.Builder.FormFlow.CommandDescription>
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
  - name: <
    nameWithType: <
    fullName: <
  - uid: Microsoft.Bot.Builder.FormFlow.FormCommand
    name: FormCommand
    nameWithType: FormCommand
    fullName: Microsoft.Bot.Builder.FormFlow.FormCommand
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: Microsoft.Bot.Builder.FormFlow.CommandDescription
    name: CommandDescription
    nameWithType: CommandDescription
    fullName: Microsoft.Bot.Builder.FormFlow.CommandDescription
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.Confirmation
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  isExternal: false
  name: Confirmation
  nameWithType: FormConfiguration.Confirmation
  fullName: FormConfiguration.Confirmation
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.CurrentChoice
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  isExternal: false
  name: CurrentChoice
  nameWithType: FormConfiguration.CurrentChoice
  fullName: FormConfiguration.CurrentChoice
- uid: System.String[]
  parent: System
  isExternal: true
  name: String[]
  nameWithType: String[]
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.DefaultPrompt
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  isExternal: false
  name: DefaultPrompt
  nameWithType: FormConfiguration.DefaultPrompt
  fullName: FormConfiguration.DefaultPrompt
- uid: Microsoft.Bot.Builder.FormFlow.PromptAttribute
  parent: Microsoft.Bot.Builder.FormFlow
  isExternal: false
  name: PromptAttribute
  nameWithType: PromptAttribute
  fullName: Microsoft.Bot.Builder.FormFlow.PromptAttribute
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.Navigation
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  isExternal: false
  name: Navigation
  nameWithType: FormConfiguration.Navigation
  fullName: FormConfiguration.Navigation
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.No
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  isExternal: false
  name: No
  nameWithType: FormConfiguration.No
  fullName: FormConfiguration.No
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.NoPreference
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  isExternal: false
  name: NoPreference
  nameWithType: FormConfiguration.NoPreference
  fullName: FormConfiguration.NoPreference
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.Template(Microsoft.Bot.Builder.FormFlow.TemplateUsage)
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  isExternal: false
  name: Template(TemplateUsage)
  nameWithType: FormConfiguration.Template(TemplateUsage)
  fullName: FormConfiguration.Template(TemplateUsage)
- uid: Microsoft.Bot.Builder.FormFlow.TemplateAttribute
  parent: Microsoft.Bot.Builder.FormFlow
  isExternal: false
  name: TemplateAttribute
  nameWithType: TemplateAttribute
  fullName: Microsoft.Bot.Builder.FormFlow.TemplateAttribute
- uid: Microsoft.Bot.Builder.FormFlow.TemplateUsage
  parent: Microsoft.Bot.Builder.FormFlow
  isExternal: false
  name: TemplateUsage
  nameWithType: TemplateUsage
  fullName: Microsoft.Bot.Builder.FormFlow.TemplateUsage
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.Templates
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  isExternal: false
  name: Templates
  nameWithType: FormConfiguration.Templates
  fullName: FormConfiguration.Templates
- uid: System.Collections.Generic.List`1
  name: List
  nameWithType: List
  fullName: System.Collections.Generic.List
- uid: System.Collections.Generic.List{Microsoft.Bot.Builder.FormFlow.TemplateAttribute}
  parent: System.Collections.Generic
  isExternal: true
  name: List<TemplateAttribute>
  nameWithType: List<TemplateAttribute>
  fullName: System.Collections.Generic.List<Microsoft.Bot.Builder.FormFlow.TemplateAttribute>
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
  - name: <
    nameWithType: <
    fullName: <
  - uid: Microsoft.Bot.Builder.FormFlow.TemplateAttribute
    name: TemplateAttribute
    nameWithType: TemplateAttribute
    fullName: Microsoft.Bot.Builder.FormFlow.TemplateAttribute
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.Yes
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  isExternal: false
  name: Yes
  nameWithType: FormConfiguration.Yes
  fullName: FormConfiguration.Yes
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.#ctor*
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  isExternal: false
  name: FormConfiguration
  nameWithType: FormConfiguration.FormConfiguration
  fullName: FormConfiguration.FormConfiguration
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Builder.FormFlow/FormConfiguration.xml
- uid: Microsoft.Bot.Builder.FormFlow.FormConfiguration.Template*
  parent: Microsoft.Bot.Builder.FormFlow.FormConfiguration
  isExternal: false
  name: Template
  nameWithType: FormConfiguration.Template
  fullName: FormConfiguration.Template
  monikers:
  - botbuilder-3.5.5
  content_git_url: https://github.com/MicrosoftDocs/bot-docs-pr/blob/AppAnalytics/dotnet/xml/Microsoft.Bot.Builder.FormFlow/FormConfiguration.xml
